development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL", "redis://127.0.0.1:6379/0") %>
  channel_prefix: <%= ENV.fetch("ACTION_CABLE_CHANNEL_PREFIX", "integration_console_development") %>
  reconnect_attempts: 5

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV["REDIS_URL"] %>
  channel_prefix: <%= ENV.fetch("ACTION_CABLE_CHANNEL_PREFIX", "integration_console_production") %>
  reconnect_attempts: 5
