default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_bin
  strict: true
  prepared_statements: true
  reconnect: false
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  connect_timeout: <%= ENV.fetch("DB_CONNECT_TIMEOUT_SECONDS", 5) %>
  read_timeout: <%= ENV.fetch("DB_READ_TIMEOUT_SECONDS", 8) %>
  write_timeout: <%= ENV.fetch("DB_WRITE_TIMEOUT_SECONDS", 8) %>
  checkout_timeout: <%= ENV.fetch("DB_CHECKOUT_TIMEOUT_SECONDS", 5) %>
  variables:
    time_zone: "+00:00"
    sql_mode: "STRICT_ALL_TABLES,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"

development:
  primary:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    database_tasks: false
  sync:
    <<: *default
    url: <%= ENV["SYNC_DATABASE_URL"] %>
    pool: <%= ENV.fetch("SYNC_DB_POOL", ENV.fetch("RAILS_MAX_THREADS", 5)) %>
    database_tasks: false

test:
  primary:
    <<: *default
    url: <%= ENV.fetch("DATABASE_URL", "mysql2://integration_console:integration_console@127.0.0.1:4000/integration_console_test") %>
    database_tasks: false
  sync:
    <<: *default
    url: <%= ENV.fetch("SYNC_DATABASE_URL", "mysql2://integration_console_read:integration_console_read@127.0.0.1:4000/octopus_core_test") %>
    pool: <%= ENV.fetch("SYNC_DB_POOL", ENV.fetch("RAILS_MAX_THREADS", 5)) %>
    database_tasks: false

production:
  primary:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    database_tasks: false
  sync:
    <<: *default
    url: <%= ENV["SYNC_DATABASE_URL"] %>
    pool: <%= ENV.fetch("SYNC_DB_POOL", ENV.fetch("RAILS_MAX_THREADS", 5)) %>
    database_tasks: false
